// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: im_api.proto

package imapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	List          []string               `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiReply) Reset() {
	*x = ApiReply{}
	mi := &file_im_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiReply) ProtoMessage() {}

func (x *ApiReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiReply.ProtoReflect.Descriptor instead.
func (*ApiReply) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{0}
}

func (x *ApiReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApiReply) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ApiReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ApiReply) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      string                 `protobuf:"bytes,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_im_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReq) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

type SendToClientReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SendUserId    string                 `protobuf:"bytes,2,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToClientReq) Reset() {
	*x = SendToClientReq{}
	mi := &file_im_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToClientReq) ProtoMessage() {}

func (x *SendToClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToClientReq.ProtoReflect.Descriptor instead.
func (*SendToClientReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{2}
}

func (x *SendToClientReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SendToClientReq) GetSendUserId() string {
	if x != nil {
		return x.SendUserId
	}
	return ""
}

func (x *SendToClientReq) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendToClientReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendToClientReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SendToClientsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIds     []string               `protobuf:"bytes,1,rep,name=client_ids,json=clientIds,proto3" json:"client_ids,omitempty"`
	SendUserId    string                 `protobuf:"bytes,2,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToClientsReq) Reset() {
	*x = SendToClientsReq{}
	mi := &file_im_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToClientsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToClientsReq) ProtoMessage() {}

func (x *SendToClientsReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToClientsReq.ProtoReflect.Descriptor instead.
func (*SendToClientsReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{3}
}

func (x *SendToClientsReq) GetClientIds() []string {
	if x != nil {
		return x.ClientIds
	}
	return nil
}

func (x *SendToClientsReq) GetSendUserId() string {
	if x != nil {
		return x.SendUserId
	}
	return ""
}

func (x *SendToClientsReq) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendToClientsReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendToClientsReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type BindToGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Extend        string                 `protobuf:"bytes,4,opt,name=extend,proto3" json:"extend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindToGroupReq) Reset() {
	*x = BindToGroupReq{}
	mi := &file_im_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindToGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindToGroupReq) ProtoMessage() {}

func (x *BindToGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindToGroupReq.ProtoReflect.Descriptor instead.
func (*BindToGroupReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{4}
}

func (x *BindToGroupReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BindToGroupReq) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *BindToGroupReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BindToGroupReq) GetExtend() string {
	if x != nil {
		return x.Extend
	}
	return ""
}

type SendToGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendUserId    string                 `protobuf:"bytes,1,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToGroupReq) Reset() {
	*x = SendToGroupReq{}
	mi := &file_im_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToGroupReq) ProtoMessage() {}

func (x *SendToGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToGroupReq.ProtoReflect.Descriptor instead.
func (*SendToGroupReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{5}
}

func (x *SendToGroupReq) GetSendUserId() string {
	if x != nil {
		return x.SendUserId
	}
	return ""
}

func (x *SendToGroupReq) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *SendToGroupReq) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendToGroupReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendToGroupReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetOnlineListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineListReq) Reset() {
	*x = GetOnlineListReq{}
	mi := &file_im_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineListReq) ProtoMessage() {}

func (x *GetOnlineListReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineListReq.ProtoReflect.Descriptor instead.
func (*GetOnlineListReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetOnlineListReq) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type CloseClientReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseClientReq) Reset() {
	*x = CloseClientReq{}
	mi := &file_im_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseClientReq) ProtoMessage() {}

func (x *CloseClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseClientReq.ProtoReflect.Descriptor instead.
func (*CloseClientReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{7}
}

func (x *CloseClientReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_im_api_proto protoreflect.FileDescriptor

const file_im_api_proto_rawDesc = "" +
	"\n" +
	"\fim_api.proto\x12\x05imapi\"y\n" +
	"\bApiReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x12\n" +
	"\x04list\x18\x05 \x03(\tR\x04list\"*\n" +
	"\vRegisterReq\x12\x1b\n" +
	"\tsystem_id\x18\x01 \x01(\tR\bsystemId\"\x8a\x01\n" +
	"\x0fSendToClientReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12 \n" +
	"\fsend_user_id\x18\x02 \x01(\tR\n" +
	"sendUserId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"\x8d\x01\n" +
	"\x10SendToClientsReq\x12\x1d\n" +
	"\n" +
	"client_ids\x18\x01 \x03(\tR\tclientIds\x12 \n" +
	"\fsend_user_id\x18\x02 \x01(\tR\n" +
	"sendUserId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"}\n" +
	"\x0eBindToGroupReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06extend\x18\x04 \x01(\tR\x06extend\"\x8b\x01\n" +
	"\x0eSendToGroupReq\x12 \n" +
	"\fsend_user_id\x18\x01 \x01(\tR\n" +
	"sendUserId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"1\n" +
	"\x10GetOnlineListReq\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\"-\n" +
	"\x0eCloseClientReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId2\x8c\x03\n" +
	"\x05ImApi\x12/\n" +
	"\bRegister\x12\x12.imapi.RegisterReq\x1a\x0f.imapi.ApiReply\x127\n" +
	"\fSendToClient\x12\x16.imapi.SendToClientReq\x1a\x0f.imapi.ApiReply\x129\n" +
	"\rSendToClients\x12\x17.imapi.SendToClientsReq\x1a\x0f.imapi.ApiReply\x125\n" +
	"\vBindToGroup\x12\x15.imapi.BindToGroupReq\x1a\x0f.imapi.ApiReply\x125\n" +
	"\vSendToGroup\x12\x15.imapi.SendToGroupReq\x1a\x0f.imapi.ApiReply\x129\n" +
	"\rGetOnlineList\x12\x17.imapi.GetOnlineListReq\x1a\x0f.imapi.ApiReply\x125\n" +
	"\vCloseClient\x12\x15.imapi.CloseClientReq\x1a\x0f.imapi.ApiReplyB\x1dZ\x1bpte_live_im/protobuf/imapib\x06proto3"

var (
	file_im_api_proto_rawDescOnce sync.Once
	file_im_api_proto_rawDescData []byte
)

func file_im_api_proto_rawDescGZIP() []byte {
	file_im_api_proto_rawDescOnce.Do(func() {
		file_im_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_api_proto_rawDesc), len(file_im_api_proto_rawDesc)))
	})
	return file_im_api_proto_rawDescData
}

var file_im_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_im_api_proto_goTypes = []any{
	(*ApiReply)(nil),         // 0: imapi.ApiReply
	(*RegisterReq)(nil),      // 1: imapi.RegisterReq
	(*SendToClientReq)(nil),  // 2: imapi.SendToClientReq
	(*SendToClientsReq)(nil), // 3: imapi.SendToClientsReq
	(*BindToGroupReq)(nil),   // 4: imapi.BindToGroupReq
	(*SendToGroupReq)(nil),   // 5: imapi.SendToGroupReq
	(*GetOnlineListReq)(nil), // 6: imapi.GetOnlineListReq
	(*CloseClientReq)(nil),   // 7: imapi.CloseClientReq
}
var file_im_api_proto_depIdxs = []int32{
	1, // 0: imapi.ImApi.Register:input_type -> imapi.RegisterReq
	2, // 1: imapi.ImApi.SendToClient:input_type -> imapi.SendToClientReq
	3, // 2: imapi.ImApi.SendToClients:input_type -> imapi.SendToClientsReq
	4, // 3: imapi.ImApi.BindToGroup:input_type -> imapi.BindToGroupReq
	5, // 4: imapi.ImApi.SendToGroup:input_type -> imapi.SendToGroupReq
	6, // 5: imapi.ImApi.GetOnlineList:input_type -> imapi.GetOnlineListReq
	7, // 6: imapi.ImApi.CloseClient:input_type -> imapi.CloseClientReq
	0, // 7: imapi.ImApi.Register:output_type -> imapi.ApiReply
	0, // 8: imapi.ImApi.SendToClient:output_type -> imapi.ApiReply
	0, // 9: imapi.ImApi.SendToClients:output_type -> imapi.ApiReply
	0, // 10: imapi.ImApi.BindToGroup:output_type -> imapi.ApiReply
	0, // 11: imapi.ImApi.SendToGroup:output_type -> imapi.ApiReply
	0, // 12: imapi.ImApi.GetOnlineList:output_type -> imapi.ApiReply
	0, // 13: imapi.ImApi.CloseClient:output_type -> imapi.ApiReply
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_im_api_proto_init() }
func file_im_api_proto_init() {
	if File_im_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_api_proto_rawDesc), len(file_im_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_api_proto_goTypes,
		DependencyIndexes: file_im_api_proto_depIdxs,
		MessageInfos:      file_im_api_proto_msgTypes,
	}.Build()
	File_im_api_proto = out.File
	file_im_api_proto_goTypes = nil
	file_im_api_proto_depIdxs = nil
}
