// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: im_api.proto

package imapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImApi_Register_FullMethodName      = "/imapi.ImApi/Register"
	ImApi_SendToClient_FullMethodName  = "/imapi.ImApi/SendToClient"
	ImApi_SendToClients_FullMethodName = "/imapi.ImApi/SendToClients"
	ImApi_BindToGroup_FullMethodName   = "/imapi.ImApi/BindToGroup"
	ImApi_SendToGroup_FullMethodName   = "/imapi.ImApi/SendToGroup"
	ImApi_GetOnlineList_FullMethodName = "/imapi.ImApi/GetOnlineList"
	ImApi_CloseClient_FullMethodName   = "/imapi.ImApi/CloseClient"
)

// ImApiClient is the client API for ImApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImApiClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*ApiReply, error)
	SendToClient(ctx context.Context, in *SendToClientReq, opts ...grpc.CallOption) (*ApiReply, error)
	SendToClients(ctx context.Context, in *SendToClientsReq, opts ...grpc.CallOption) (*ApiReply, error)
	BindToGroup(ctx context.Context, in *BindToGroupReq, opts ...grpc.CallOption) (*ApiReply, error)
	SendToGroup(ctx context.Context, in *SendToGroupReq, opts ...grpc.CallOption) (*ApiReply, error)
	GetOnlineList(ctx context.Context, in *GetOnlineListReq, opts ...grpc.CallOption) (*ApiReply, error)
	CloseClient(ctx context.Context, in *CloseClientReq, opts ...grpc.CallOption) (*ApiReply, error)
}

type imApiClient struct {
	cc grpc.ClientConnInterface
}

func NewImApiClient(cc grpc.ClientConnInterface) ImApiClient {
	return &imApiClient{cc}
}

func (c *imApiClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*ApiReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, ImApi_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imApiClient) SendToClient(ctx context.Context, in *SendToClientReq, opts ...grpc.CallOption) (*ApiReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, ImApi_SendToClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imApiClient) SendToClients(ctx context.Context, in *SendToClientsReq, opts ...grpc.CallOption) (*ApiReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, ImApi_SendToClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imApiClient) BindToGroup(ctx context.Context, in *BindToGroupReq, opts ...grpc.CallOption) (*ApiReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, ImApi_BindToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imApiClient) SendToGroup(ctx context.Context, in *SendToGroupReq, opts ...grpc.CallOption) (*ApiReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, ImApi_SendToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imApiClient) GetOnlineList(ctx context.Context, in *GetOnlineListReq, opts ...grpc.CallOption) (*ApiReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, ImApi_GetOnlineList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imApiClient) CloseClient(ctx context.Context, in *CloseClientReq, opts ...grpc.CallOption) (*ApiReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, ImApi_CloseClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImApiServer is the server API for ImApi service.
// All implementations must embed UnimplementedImApiServer
// for forward compatibility.
type ImApiServer interface {
	Register(context.Context, *RegisterReq) (*ApiReply, error)
	SendToClient(context.Context, *SendToClientReq) (*ApiReply, error)
	SendToClients(context.Context, *SendToClientsReq) (*ApiReply, error)
	BindToGroup(context.Context, *BindToGroupReq) (*ApiReply, error)
	SendToGroup(context.Context, *SendToGroupReq) (*ApiReply, error)
	GetOnlineList(context.Context, *GetOnlineListReq) (*ApiReply, error)
	CloseClient(context.Context, *CloseClientReq) (*ApiReply, error)
	mustEmbedUnimplementedImApiServer()
}

// UnimplementedImApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImApiServer struct{}

func (UnimplementedImApiServer) Register(context.Context, *RegisterReq) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedImApiServer) SendToClient(context.Context, *SendToClientReq) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToClient not implemented")
}
func (UnimplementedImApiServer) SendToClients(context.Context, *SendToClientsReq) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToClients not implemented")
}
func (UnimplementedImApiServer) BindToGroup(context.Context, *BindToGroupReq) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindToGroup not implemented")
}
func (UnimplementedImApiServer) SendToGroup(context.Context, *SendToGroupReq) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToGroup not implemented")
}
func (UnimplementedImApiServer) GetOnlineList(context.Context, *GetOnlineListReq) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnlineList not implemented")
}
func (UnimplementedImApiServer) CloseClient(context.Context, *CloseClientReq) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseClient not implemented")
}
func (UnimplementedImApiServer) mustEmbedUnimplementedImApiServer() {}
func (UnimplementedImApiServer) testEmbeddedByValue()               {}

// UnsafeImApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImApiServer will
// result in compilation errors.
type UnsafeImApiServer interface {
	mustEmbedUnimplementedImApiServer()
}

func RegisterImApiServer(s grpc.ServiceRegistrar, srv ImApiServer) {
	// If the following call pancis, it indicates UnimplementedImApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImApi_ServiceDesc, srv)
}

func _ImApi_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImApiServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImApi_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImApiServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImApi_SendToClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImApiServer).SendToClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImApi_SendToClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImApiServer).SendToClient(ctx, req.(*SendToClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImApi_SendToClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToClientsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImApiServer).SendToClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImApi_SendToClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImApiServer).SendToClients(ctx, req.(*SendToClientsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImApi_BindToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindToGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImApiServer).BindToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImApi_BindToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImApiServer).BindToGroup(ctx, req.(*BindToGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImApi_SendToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImApiServer).SendToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImApi_SendToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImApiServer).SendToGroup(ctx, req.(*SendToGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImApi_GetOnlineList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImApiServer).GetOnlineList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImApi_GetOnlineList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImApiServer).GetOnlineList(ctx, req.(*GetOnlineListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImApi_CloseClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImApiServer).CloseClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImApi_CloseClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImApiServer).CloseClient(ctx, req.(*CloseClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ImApi_ServiceDesc is the grpc.ServiceDesc for ImApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imapi.ImApi",
	HandlerType: (*ImApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ImApi_Register_Handler,
		},
		{
			MethodName: "SendToClient",
			Handler:    _ImApi_SendToClient_Handler,
		},
		{
			MethodName: "SendToClients",
			Handler:    _ImApi_SendToClients_Handler,
		},
		{
			MethodName: "BindToGroup",
			Handler:    _ImApi_BindToGroup_Handler,
		},
		{
			MethodName: "SendToGroup",
			Handler:    _ImApi_SendToGroup_Handler,
		},
		{
			MethodName: "GetOnlineList",
			Handler:    _ImApi_GetOnlineList_Handler,
		},
		{
			MethodName: "CloseClient",
			Handler:    _ImApi_CloseClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im_api.proto",
}
